### ISSUE TITLE
공통 헤더 / 풋터 생성

### ISSUE THREAD

**Issue by her9797** [reValuper/revelup#11]
**## 문제 제기**
- 풋터와 헤더를 공통으로 사용할 수 있도록 적절한 위치 및 예정 기능 추가

**## 기능 요약**
- 헤더 생성
- 풋터 생성

**## 기능 설명**
- 헤더 : 공통으로 사용하여, 해당 버튼, 카테고리 클릭 시 접속 할 수 있도록 생성
- 풋터 : 기획 단계와 동일한 디자인 및 버튼들을 생성하여 부가 기능들로 접속 할 수 있도록 생성

**## TO-DO 리스트**
- [x] 헤더의 css, 확인 및 버튼 위치 수정 및 생성
- [x] 풋터 공통 css 생성
- [x] 소스 공유 및 배치 구성 확인

**## 비고**
- 시큐리티로 인한 헤더의 마이페이지 버튼이 없어 test용으로 생성해두었음.
