### ISSUE TITLE
[펀딩 신규 등록] 세터정보 입력 페이지 제작

### ISSUE THREAD

**Issue by JayLee-98** [reValuper/revelup#13]
**## 문제 제기**
- 세터의 정보를 입력받기 위한 페이지 제작

**## 기능 요약**
- 여러 input을 받고, 그 input을 설명하는 라벨 필요

**## 기능 설명**
- 여러 input을 받고, 그 input을 설명하는 라벨 필요
- 입력 타입에 따라 input type을 숫자 혹은 텍스트로 받을 것인지 설정 필요
- 각각 이전 페이지와 다음 페이지를 클릭시 관련 페이지로 이동할 수 있도록 링크 연결

**## TO-DO 리스트**
- [x] 사업자 등록 번호, 상호, 대표자명 라벨 생성
- [x] input type으로 숫자와 텍스트로 인풋창 생성
- [x] 이전과 다음 버튼 생성 및 관련 페이지로 연결

**## 비고**
- 여기에 해당 기능에 대한 스크린샷이나 상세 설명, 레퍼런스 등을 작성해주세요. (선택)
![image](https://github.com/reValuper/revelup/assets/153487581/a764cbab-c9df-413c-9f5c-9d99abe5830c)
