### ISSUE TITLE
[신규 펀딩 등록] 펀딩에 대한 기본 정보 입력 페이지 생성

### ISSUE THREAD

**Issue by JayLee-98** [reValuper/revelup#15]
**## 문제 제기**
- 펀딩에 대한 기본 정보 입력 페이지 생성

**## 기능 요약**
- 인풋과 라벨
- 이미지 업로드

**## 기능 설명**
- 인풋과 해당하는 인풋에 대한 라벨 생성
- 이미지 파일 업로드 할 수 있도록 파일 업로더
- 입력값을 숫자, 텍스트, 파일, 날짜로 받을 수 있도록 각기 다른 input type 설정

**## TO-DO 리스트**
- [x] 펀딩명, 대표이미지, 펀딩 종료일, 목표 금액 라벨 생성
- [x] 인풋창 너비와 높이 지정
- [ ] 이미지 파일 업로드시 이미지 너비와 높이 지정
- [ ] 레이아웃으로 이미지가 들어갈 공간이 보이는 것이 아니라, 파일이 추가 될 때 마다 이미지 미리보기가 추가
- [ ] 업로드한 이미지의 미리보기를 드래그앤드롭 형식으로 순서 변경
- [x] 펀딩 종료일 설정을 위해 날짜를 (1) 입력할때 직접 키패드로 날짜 작성, (2) 캘린더를 클릭형식으로 날짜를 마우스로 입력

**## 비고**
- 여기에 해당 기능에 대한 스크린샷이나 상세 설명, 레퍼런스 등을 작성해주세요. (선택)
![image](https://github.com/reValuper/revelup/assets/153487581/41f749c5-f96f-4440-ac77-42f2aace47a5)
