### ISSUE TITLE
[펀딩 신규 등록] 등록 완료 페이지 제작

### ISSUE THREAD

**Issue by JayLee-98** [reValuper/revelup#18]
**## 문제 제기**
- 필요 정보와 파일을 입력했을 경우 보여지는 페이지 제작

**## 기능 요약**
- 등록 완료를 보여주는 페이지

**## 기능 설명**
- 등록 완료를 보여주는 페이지

**## TO-DO 리스트**
- [x] 이미지를 불러와 체크 이미지 삽입
- [x] 등록이 완료되었다는 안내문 작성
- [x] 버튼을 누르면 해당 페이지로 이동할 수 있도록 버튼 삽입
- [x] 버튼에 해당 페이지 경로로 연결

**## 비고**
- 여기에 해당 기능에 대한 스크린샷이나 상세 설명, 레퍼런스 등을 작성해주세요. (선택)
![image](https://github.com/reValuper/revelup/assets/153487581/4cda617d-0102-4ae0-bbd8-6266f62e77da)
