### ISSUE TITLE
[전체 펀딩 조회] 현재 진행중인 전체 펀딩 조회 페이지 제작 

### ISSUE THREAD

**Issue by JayLee-98** [reValuper/revelup#19]
**## 문제 제기**
- 헤더 전체 제품을 누르면 전체 펀딩을 조회할 수 있는 페이지 제작

**## 기능 요약**
- 전체 진행 중인 펀딩의 리스트를 한 눈에 확인 할 수 있는 페이지

**## 기능 설명**
- 펀딩에 대략적인 정보 (펀딩명, 달성율, 후원 금액, 후원하기 버튼, 찜하기 버튼)을 카드 형식 표현하기 위해 하나의 div안에 작성
- 각 버튼을 누르면 선택된 펀딩의 페이지로 이동 하거나 '찜하기 저장' 구현

**## TO-DO 리스트**
- [x] 불러올 이미지를 경로에 다운로드
- [x] progress 태그 혹은 bootstrap을 사용하여 가로 그래프 구현
- [x] 각 버튼을 누르면 상세 페이지로 이동

**## 비고**
- 여기에 해당 기능에 대한 스크린샷이나 상세 설명, 레퍼런스 등을 작성해주세요. (선택)
![image](https://github.com/reValuper/revelup/assets/153487581/34ded1fb-16d9-4cde-abbd-da330b142e51)

**Comment by JayLee-98** [comment]
progress 태그 관련 참고: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress
