### ISSUE TITLE
[상세 페이지] 상세 페이지 제작

### ISSUE THREAD

**Issue by JayLee-98** [reValuper/revelup#20]
**## 문제 제기**
- 펀딩 상세 정보를 조회, 수량 선택 후 후원, 찜하기, 신고하기, 게터가 세터에게 카톡 상담할 수 있는 상세 페이지 제작

**## 기능 요약**
- 대표 이미지들(썸네일)을 버튼을 눌러서 슬라이드 형식으로 확인 가능
- 선물 수량 선택
- 달성율 확인 가능
- 찜하기 버튼, 후원하기 버튼. 신고하기 버튼, 카톡 상담하기 버튼
- 현재까지 참여한 후원자 수, 모금 달성액, 펀딩 마감일, 남은 펀딩 기간, 모금액 달성시 펀딩 예상 발송일 확인 가능한 표
- 세터 프로필 사진
- 펀딩 스토리
- 펀딩 공지사항
- 상세 이미지

**## 기능 설명**
- 대표 이미지에 이전, 다음 버튼을 오버레이하여 각 버튼을 눌렀을때 대표 이미지가 회전하도록 구현
- 선물 수량을 +, - 를 마우스로 클릭하여 수량 조정
- 수량에 따라 총 후원 금액이 자동 계산되어 보여지도록 구현
- 게터들이 후원함에 따라 달성율이 자동 수정될 수 있도록 구현
- 세터가 등록한 이미지, 세터 프로필 사진, 펀딩 스토리, 공지사항, 상세 이미지 등을 불러와서 보여질 수 있도록 구현

**## TO-DO 리스트**
- [x] 대표 이미지 위에 버튼을 오버레이해서 버튼의 position: absolute; 이후 위치는 top bottom: x%;로 구현
- [x] progress inline element 혹은 bootstrap을 활용하여 달성율 구현
- [x] 선물 수량 입력 인풋 (+, -, 숫자 인풋으로 구분하고 숫자 인풋란은 readonly 속성을 걸어서 +,- 버튼으로만 조작할 수 있도록 구현)
- [x] 각종 버튼을 누르면 해당 페이지로 연결

**## 비고**
- 여기에 해당 기능에 대한 스크린샷이나 상세 설명, 레퍼런스 등을 작성해주세요. (선택)
![image](https://github.com/reValuper/revelup/assets/153487581/6848e0d7-26c7-43ab-b1ff-637c4402fce8)
