### ISSUE TITLE
[매니저 펀딩 조회 페이지] DB에서 펀딩 목록 조회

### ISSUE THREAD

**Issue by JayLee-98** [reValuper/revelup#47]
**## 문제 제기**
- 매니저가 현재 진행 중인 전체 펀딩 목록을 간결하게 볼 수 있도록 매니저용 펀딩 조회 페이지 제작

**## 기능 요약**
- 펀딩 조회 페이지 제작
- 필터를 선택했을때 각 상태에 맞는 펀딩만 보여줄 수 있도록 JS, 쿼리 작성

**## 기능 설명**
- 진행 중, 대기 중, 종료 등 상태에 따른 필터 선택시 해당하는 펀딩만 조회 될 수 있는 페이지

**## TO-DO 리스트**
- [x] DB에서 select하는 쿼리 작성
- [x] HTML, CSS, JS 작성
- [x] 필터 버튼 생성 및 필터로 상태 선택 시 진행 중, 대기 중, 종료된 펀딩 만 보여줄 수 있도록 구현

**## 비고**
![image](https://github.com/reValuper/revelup/assets/153487581/ddc86cdc-2ed4-454a-a544-7986acb9ba29)
