### ISSUE TITLE
마이페이지 후원철회 및 철회 내역 페이지 생성

### ISSUE THREAD

**Issue by KIMHYEONJI13** [reValuper/revelup#5]
**## 문제 제기**
- 후원철회에 대한 페이지 연결 및 제작이 부족하여 해당 부분을 생성

**## 기능 요약**
- 마이페이지  후원철회 및 철회 내역 페이지 연결

**## 기능 설명**
- 후원 철회에 대한 내역 

**## TO-DO 리스트**
- [ ] 후원철회 모달 생성, 연결
- [ ] 철회사유 선택지 생성
- [ ] 철회내역 페이지 생성 및 연결

**## 비고**
- 후원 철회 신청 후 철회 내역에서 해당 이유를 확인 할 수 있게 데이터 전달 필요
