### ISSUE TITLE
메인 / 로그인 화면 생성

### ISSUE THREAD

**Issue by her9797** [reValuper/revelup#7]
**## 기능 요약**
- 메인 / 로그인 화면을 HTML과 CSS를 사용하여 생성하였습니다.

**## 기능 설명**
- 메인페이지의 버튼들을 클릭하면 해당 페이지로 이동할 수 있도록 링크를 걸어주었습니다.
- 해당 화면이 기획단계에서 구성하고자 했던 곳에 적절히 배치해주었습니다.

**## TO-DO 리스트**
- [x] 로그인 버튼 클릭 시 로그인 화면으로 전환
- [x] 회원가입 버튼 클릭 시 회원가입 화면으로 전환
- [x] 메인페이지에서의 모달창, 오류발생 여부 확인

**## 비고**
- 로그인 시도 시 발생하는 오류 건은 백단 시큐리티 작업 시에 함께 진행할 예정입니다.
